openapi: 3.0.1
info:
  title: Caterfab DXF Plugin API
  description: API for uploading, extracting, and modifying DXF files for Caterfab
  version: "1.0.0"
servers:
  - url: https://yourdomain.com
paths:
  /upload_dxf:
    post:
      summary: Upload a DXF file
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Upload successful
  /extract_data:
    get:
      summary: Extract entity data from uploaded DXF
      parameters:
        - in: query
          name: filename
          schema:
            type: string
          required: true
      responses:
        '200':
          description: List of entities found
  /amend_drawing:
    post:
      summary: Apply modifications to a DXF
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                filename:
                  type: string
                new_length:
                  type: number
      responses:
        '200':
          description: Drawing modified and downloadable link provided
  /download_dxf:
    get:
      summary: Download a modified DXF
      parameters:
        - in: query
          name: filename
          schema:
            type: string
          required: true
      responses:
        '200':
          description: DXF file returned