openapi: "3.1.0"
info:
  title: Caterfab DXF Plugin API
  description: API for uploading, extracting, and modifying DXF files for Caterfab
  version: "1.0.0"
servers:
  - url: https://caterfab-dxf-plugin.onrender.com
paths:
  /upload_dxf:
    post:
      summary: Upload a DXF file
      operationId: upload_dxf
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Upload successful

  /extract_data:
    get:
      summary: Extract entity data from uploaded DXF
      operationId: extract_data
      parameters:
        - in: query
          name: filename
          schema:
            type: string
          required: true
      responses:
        '200':
          description: List of entities found

  /amend_drawing:
    post:
      summary: Apply modifications to a DXF
      operationId: amend_drawing
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                filename:
                  type: string
                new_length:
                  type: number
      responses:
        '200':
          description: Drawing modified and downloadable link provided

  /download_dxf:
    get:
      summary: Download a modified DXF
      operationId: download_dxf
      parameters:
        - in: query
          name: filename
          schema:
            type: string
          required: true
      responses:
        '200':
          description: DXF file returned
